# kind-cilium.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  disableDefaultCNI: true
  kubeProxyMode: none   # important for Cilium (eBPF replaces kube-proxy)

nodes:
  - role: control-plane
  - role: worker
  - role: worker
