apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: all-in-one-playground
  namespace: default
spec:
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:

      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 80

      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep infinity"]

      - name: alpine
        image: alpine
        command: ["sh", "-c", "sleep infinity"]

      - name: ubuntu
        image: ubuntu:22.04
        command: ["bash", "-c", "sleep infinity"]

      - name: redis
        image: redis:7-alpine
        ports:
          - containerPort: 6379

      - name: mysql
        image: mysql:8
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: rootpass
        ports:
          - containerPort: 3306

      - name: mongodb
        image: mongo:7
        ports:
          - containerPort: 27017

      - name: postgresql
        image: postgres:16
        env:
          - name: POSTGRES_PASSWORD
            value: postgrespass
        ports:
          - containerPort: 5432
